name: Build Niyanta — Windows, macOS, Linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install mediapipe opencv-python pyautogui numpy Pillow pycaw comtypes screen-brightness-control pyinstaller
      - name: Build Niyanta.exe
        run: pyinstaller --onefile --noconsole --name "Niyanta" --icon "icon.ico" --collect-all mediapipe --collect-all google --add-data "hand_landmarker.task;." main.py
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-Niyanta
          path: dist/Niyanta.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install mediapipe opencv-python pyautogui numpy Pillow screen-brightness-control pyinstaller
      - name: Build Niyanta
        run: pyinstaller --onefile --noconsole --name "Niyanta" --icon "icon.icns" --collect-all mediapipe --collect-all google --add-data "hand_landmarker.task:." main.py
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-Niyanta
          path: dist/Niyanta

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: System packages
        run: sudo apt-get update && sudo apt-get install -y alsa-utils python3-tk libgl1
      - name: Install deps
        run: pip install mediapipe opencv-python pyautogui numpy Pillow screen-brightness-control pyinstaller
      - name: Build Niyanta
        run: pyinstaller --onefile --name "Niyanta" --collect-all mediapipe --collect-all google --add-data "hand_landmarker.task:." main.py
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-Niyanta
          path: dist/Niyanta
